#!/bin/bash

# Install preferred apps
function install_apt_apps {
	# Update the list of packages in 'data/favs.list' to suit your preferences
	install_from_list_apt "Apt Apps" "apt" main
}

function install_snap_apps {
	# Update the list of packages in 'data/favs.list' to suit your preferences
	install_from_list_snap "Snap Apps" "snap" main
}

# install app from flathub repository
function install_flathub_app() {
	echo_message header "Starting 'install_flathub_app' function..."
	# check if flathub repo is added
	check_flatpak_repo "flathub" "https://flathub.org/repo/flathub.flatpakrepo" install_flatpak_apps
	#install_flatpak_package "Name" "remote" "com.package.Name" return_function
	install_flatpak_package ${1} "flathub" ${2} install_flatpak_apps
}

# Install Flatpak Applications
function install_flatpak_apps {
	# check if 'flatpak' is installed
	check_package "flatpak" main
	# install
	NAME="Flatpak Applications"
	echo_message title "Starting installation of ${NAME,,}..."
	status="0"
	while [ "$status" -eq 0 ]; do
		# Draw window
		FLATPAKS=$(eval `resize` && whiptail \
			--notags \
			--title "Install $NAME" \
			--menu "\nWhat ${NAME,,} would you like to install?" \
			--ok-button "Install" \
			--cancel-button "Go Back" \
			$LINES $COLUMNS $(( $LINES - 9 )) \
			'install_flatpak_dropbox'   'Dropbox' \
			'install_flatpak_chrome'    'Chrome' \
			'install_flatpak_github'    'GitHub' \
			'install_flatpak_discord'   'Discord' \
			'install_flatpak_telegram'  'Telegram' \
			'install_flatpak_signal'    'Signal' \
			'install_flatpak_bottles'   'Bottles' \
			'install_flatpak_obs'       'OBS' \
			'install_flatpak_kdenlive'  'Kdenlive' \
			'install_flatpak_audacity'  'Audacity' \
			'install_flatpak_zoom'      'zoom' \
			'install_flatpak_whatsapp'  'Whatsapp' \
			'install_flatpak_anydesk'   'Anydesk' \
			'install_flatpak_thundrbird''Thunderbird' \
			'install_flatpak_gimp'      'Gimp' \
			'install_flatpak_krita'     'Krita' \
			3>&1 1>&2 2>&3)

		case "${FLATPAKS}" in
			install_flatpak_dropbox)
				# install Dropbox
				install_flathub_app "Dropbox" "com.dropbox.Client"
				;;
			install_flatpak_chrome)
				# install Google Chrome
				install_flathub_app "Chrome" "com.google.Chrome"
				;;
			install_flatpak_github)
				# install GitHub Desktop
				install_flathub_app "GitHub Desktop" "io.github.shiftey.Desktop"
				;;
			install_flatpak_discord)
				# install Discord
				install_flathub_app "Discord" "com.discordapp.Discord"
				;;
			install_flatpak_telegram)
				# install Telegram
				install_flathub_app "Telegram" "org.telegram.desktop"
				;;
			install_flatpak_signal)
				# install Signal
				install_flathub_app "Signal" "org.signal.Signal"
				;;
			install_flatpak_bottles)
				# install Bottles
				install_flathub_app "Bottles" "com.usebottles.bottles"
				;;
			install_flatpak_obs)
				# install Steam
				install_flathub_app "OBS" "com.obsproject.Studio"
				;;
			install_flatpak_kdenlive)
				# install GIMP
				install_flathub_app "Kdenlive" "org.kde.kdenlive"
				;;
			install_flatpak_audacity)
				# install Peek
				install_flathub_app "Audacity" "org.audacityteam.Audacity"
				;;
			install_flatpak_zoom)
				# install Riot chat
				install_flathub_app "Zoom" "us.zoom.zoom"
				;;
			install_flatpak_whatsapp)
				# install Steam
				install_flathub_app "Whatsapp" "io.github.mimbrero.WhatsAppDesktop"
				;;
			install_flatpak_anydesk)
				# install GIMP
				install_flathub_app "Anydesk" "com.anydesk.Anydesk"
				;;
			install_flatpak_thundrbird)
				# install Peek
				install_flathub_app "Thunderbird" "org.mozilla.Thunderbird"
				;;
			install_flatpak_gimp)
				# install Riot chat
				install_flathub_app "Gimp" "org.gimp.GIMP"
				;;
			install_flatpak_krita)
				# install Steam
				install_flathub_app "Krita" "org.kde.krita"
				;;
			*) 
				# cancel
				echo_message info "Returning..."
				status=1
				main
			;;
		esac
	done
}



