#!/bin/bash

# Install Cuda 12.1 
wget -P ~/Downloads/ https://developer.download.nvidia.com/compute/cuda/12.1.0/local_installers/cuda_12.1.0_530.30.02_linux.run
sudo sh ./Downloads/cuda_12.1.0_530.30.02_linux.run